<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="comvamp.db" nsURI="https://org.haeqs.comvamp.db" nsPrefix="comvamp.db">
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inResponseTo" lowerBound="1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishedOn" lowerBound="1"
        eType="#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasDetails" upperBound="-1"
        eType="#//CommentDetails"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishedBy" lowerBound="1"
        eType="#//Author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeOn" lowerBound="1"
        upperBound="-1" eType="#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasDetails" upperBound="-1"
        eType="#//AuthorDetails"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Platform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishedOn" lowerBound="1"
        eType="#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasDetails" upperBound="-1"
        eType="#//ArtifactDetails"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthorDetails">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentDetails">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactDetails">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
